### ISSUE TITLE
Selecting All Channels

### ISSUE THREAD

**Issue by CLJackson13** [JinmiaoChenLab/cytofkit#18]
Hi, 

I have been using your program for months and today I had an issue with performing the analysis. 

I selected all of my files (8) and markers (25) as usual but the program analyzed all 62 possible channels, so my results didn't make any sense. 

I tried updating R, manually typing in the parameters with the cytofkit function, updating bioconductor, restarting my computer, and reinstalling the package. Nothing seems to work. 

Despite the output showing only the markers I selected, it still extracts all 62 channels for me:
Extract expression data...
   40000  x  62  data was extracted!
Dimension reduction...
  Running t-SNE...with seed 42

Can you help me figure out what is happening?

Thank you

**Comment by jinmiaochen** [comment]
Dear Jackson,

Thanks for your feedback. We recently updated the package to allow visualizing all markers with shinyapp while using only selected markers for tSNE and clustering. Matthew (cc’ed) is currently in charge of the package and he will follow up with you. Maybe we should probably state “Running t-SNE using selected n markers”.

Best
Jinmiao

**Comment by MattMyint** [comment]
Hi Jackson!

It is as Jinmiao mentioned. At the expression data extraction, it does extract all 62 channels.

However, only your selected 25 markers are used for dimension reduction and clustering.

But yes, it can cause some confusion especially for users who were used to the old cytofkit, so I'll add a line to state how many markers were used for dimension reduction and clustering

Regards
Matthew

**Comment by CLJackson13** [comment]
Thank you for your quick response. Based on what I am seeing, the clusters are being created based on all 62 parameters because I performed this analysis a few months ago and the results are remarkably different. Each file seems to have the majority of cells contained in one cluster and there is a total of 65 clusters. The previous analysis with the same parameters and files had 35 clusters. We are looking at two different time points and even those, which should have some similar populations do not have any similar populations. 

Can you help me figure this out?

Thank you for your help, 

Conner

I have attached the different in tsne plots 
![oldanalysis35clusters](https://user-images.githubusercontent.com/33847074/33090082-01796c6a-ceb0-11e7-80ce-faf9007c4764.png)
![newanalysis65clusters](https://user-images.githubusercontent.com/33847074/33090121-1c91dc8a-ceb0-11e7-9ea7-dc8f9e31cdee.png)

**Comment by MattMyint** [comment]
Which version of cytofkit are you using currently? We've had [reported issues with version 1.8.3](https://github.com/JinmiaoChenLab/cytofkit/issues/11). Updating should resolve the issue.

 You can update using the following steps
```
source("https://bioconductor.org/biocLite.R")
biocLite()
```

**Comment by CLJackson13** [comment]
Still not working, there seems to be an issue with the package Destiny on windows after looking at Bioconductor
Perhaps this is the problem? I am updated to version 3.6 for Bioconductor but am getting this output despite the fact that I am an administrator:

Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.2 (2017-09-28).
installation path not writeable, unable to update packages: Matrix,
  mgcv
Old packages: 'destiny'

Any ideas?

Thank you for all of your help

**Comment by SamGG** [comment]
Hi,
This sounds like a typical error under Windows.
https://stackoverflow.com/questions/28546382/installed-directory-not-writable-cannot-update-packages-boot-class-kerns
https://support.bioconductor.org/p/96834/
Before running R as administrator or not, just close all your R/RStudio programs, then start a new R/RStudio session, without any project nor data loaded in order to avoid the automatic loading of some libraries. Alternatively, start a single new empty project. Then try to update the packages you need.
HTH

**Comment by MattMyint** [comment]
Hi @CLJackson13 is the cytofkit updating still unsuccessful?

**Comment by CLJackson13** [comment]
Hi Matt, 

I apologize for the lateness of my response, I haven't had time to follow up on this. I will check it out by Friday and let you know how it goes. I'm sure the recommendation by @SamGG will resolve the issue. 

Thank you again for your help

**Comment by CLJackson13** [comment]
Everything works great now, thank you. Apologies for taking so long to respond
